### ISSUE TITLE
Nextclade issue during analysis

### ISSUE THREAD

**Issue by ghost** [charlesfoster/covid-illumina-snakemake#2]
Hi Dr. Foster.

After running the Snakefile for a bit, I got this error:
![image](https://user-images.githubusercontent.com/91744154/168640699-2f0c74ef-0ea3-42d3-ae17-b37c49128eeb.png)

I installed nextcalde cli into the same directory as CIS. When I restarted the snakefile, I received this:

![image](https://user-images.githubusercontent.com/91744154/168640869-d2cf5fe3-e6df-4809-9687-bcf17b58e6bf.png)

Any thoughts?

**Comment by charlesfoster** [comment]
Hi,

Please copy and paste the error text as well (or instead) - makes it easier to tell what's going on. Also, please run with the `--verbose`flag, i.e. `CIS --verbose ./runs`. Make sure you're using the correct amplicon scheme too. For now:

**Nextclade**
You shouldn't need to manually install `nextclade`, and if you do, it likely won't be used by CIS anyway.  The rule within the Snakefile uses `singularity` to run a docker container specified within the `nextclade` rule: docker://nextstrain/nextclade:latest. 

I can't really know what wrong for you unless you find an error message. You'll see that a file "nextclade_update_info.txt" should've been created. What does that file say?

If that doesn't help, try running the singularity container directly. It'll be in the directory `/path/to/covid-illumina-snakemake/.snakemake/singularity` and have the extension ".simg".  

With the CIS conda environment activated, try running:

```
export OUTDIR=/path/to/analysis/outdir 
singularity run -B --bind ${OUTDIR}:${OUTDIR},${CONDA_PREFIX}:${CONDA_PREFIX}  \
/path/to/covid-illumina-snakemake/.snakemake/singularity/XXXXXXXX.simg \
        nextclade --version >> debugging.txt
        echo "Updating SARS-CoV-2 dataset..." >> debugging.txt
        nextclade dataset get --name sars-cov-2 -o nextclade_debugging &>> debugging.txt
```
Take note of whatever is printed to the terminal screen and what is in debugging.txt afterwards. If it works fine, I don't know what the issue is.

**snpEff**
Your error suggests an internet connection error to the snpEff databases/website while it tries to download the SARS-CoV-2 database, not an issue with the pipeline. Try running the pipeline again to see if it works this time, or (like above) manually run the snpEff command while in the CIS conda environment and see what happens.

Cheers,
Charles

**Comment by ghost** [comment]
HI Dr. Foster. I ran the pipeline again today...and it ran perfectly!

Thanks for your help. I'm going to close this issue.
